### ISSUE TITLE
incorrect result or no solution about your algorithm but others have

### ISSUE THREAD

**Issue by BossunWang** [g9nkn/p3p_problem#1]
Hi, expert
I found out this issue following the example:

w = 1024;
h = 576;
f = 1024;
K = [f, 0, w/2
     0, f, h/2
     0, 0,  1];
pts2d = [359, 337, 513
         391, 297, 301
         1, 1, 1];
normalized_pts2d = K\pts2d;

pts3d = [0, -225, 225
         0,  170, 170
         0, -135, -135];

then the results:
Gao:

R_est
ans(:,:,1) =

   0.7792449   0.0536202  -0.6244216
   0.0097686  -0.9972514  -0.0734450
  -0.6266435   0.0511319  -0.7776268

ans(:,:,2) =

   0.542427   0.836628   0.076328
   0.022971  -0.105592   0.994144
   0.839789  -0.537497  -0.076494

ans(:,:,3) =

   0.22749   0.96596  -0.12318
  -0.12270   0.15392   0.98044
   0.96602  -0.20793   0.15353

ans(:,:,4) =

   0.22749   0.96596  -0.12318
  -0.12270   0.15392   0.98044
   0.96602  -0.20793   0.15353
t_est
   -267.024   -252.215   -134.898   -134.898
    179.761    169.792     82.108     82.108
   1787.140   1688.025    236.743    236.743
2

Ke:

R_est
ans(:,:,1) =

   0.542427   0.836628   0.076328
   0.022971  -0.105592   0.994144
   0.839789  -0.537497  -0.076494

ans(:,:,2) =

   0.7792449   0.0536202  -0.6244216
   0.0097686  -0.9972514  -0.0734450
  -0.6266435   0.0511319  -0.7776268

ans(:,:,3) =

   0.8669231   0.0317591  -0.5828044
   0.0077235  -1.3678931  -0.5003661
  -0.9452539   0.3515464  -1.0637398

ans(:,:,4) =

   0.8669231   0.0317591  -0.5828044
   0.0077235  -1.3678931  -0.5003661
  -0.9452539   0.3515464  -1.0637398
t_est
   -252.21   -267.02   -277.33   -277.33
    169.79    179.76    186.70    186.70
   1688.03   1787.14   1856.13   1856.13
3

Nakano:

R_est
[](3x3x0)
t_est
[](3x0)

when I comment this line :
https://github.com/g9nkn/p3p_problem/blob/b99e6f1b99f89de27d8d8a0cbb47cb83f00afc60/p3p_nakano_bmvc2019.m#L91

R_est
ans(:,:,1) =

   0.999242 - 0.000028i  -0.210825 + 0.595533i   0.412655 - 0.667384i
   0.022547 - 0.000368i  -5.173041 + 3.220268i  -6.070189 + 5.009939i
  -0.012858 - 0.029012i   6.105178 - 5.024745i  -5.188853 + 3.207036i

ans(:,:,2) =

   0.999242 + 0.000028i  -0.210825 - 0.595533i   0.412655 + 0.667384i
   0.022547 + 0.000368i  -5.173041 - 3.220268i  -6.070189 - 5.009939i
  -0.012858 + 0.029012i   6.105178 + 5.024745i  -5.188853 - 3.207036i

ans(:,:,3) =

   0.101498  -0.046738  -0.035541
  -0.010300  -0.013397   0.081891
  -0.994782  -0.323205   0.248512

ans(:,:,4) =

   0.068111  -0.094545   0.141373
  -0.011095   0.127683   0.069906
  -0.997616   0.316565  -0.248769
t_est
 Columns 1 through 3:

   -130.732 -  191.344i   -130.732 +  191.344i    -19.865 +    0.000i
     88.009 +  128.813i     88.009 -  128.813i     13.373 +    0.000i
    874.961 + 1280.629i    874.961 - 1280.629i    132.952 +    0.000i

 Column 4:

19.571 +    0.000i
-13.175 +    0.000i
-130.987 +    0.000i

this result is different with another algorithm

**Comment by g9nkn** [comment]
Please try it again with L2 normalization on each 2D point:
[R, t] = p3p_nakano_bmvc2019( normalized_pts2d./vecnorm(normalized_pts2d), pts3d ).
I got the same real solution as Ke and Gao. You don't need to comment out Line 91 to obtain both real and complex solutions.

As shown in my paper and the demo code, some p3p solvers assume that each 2D point m_i is numerically normalized such that || m_i ||^2 = 1.

**Comment by BossunWang** [comment]
thanks your reply,
I understand which your points, but this line has been used L2 normalization
https://github.com/g9nkn/p3p_problem/blob/b99e6f1b99f89de27d8d8a0cbb47cb83f00afc60/demo_p3p_nakano_bmvc2019.m#L36

May you post your demo code to check?

**Comment by g9nkn** [comment]
I'm using `demo_p3p_nakano_bmvc2019.m` to run simple tests. Did you try my answer to confirm that you can get the correct solution?

**Comment by BossunWang** [comment]
Thanks your reply again,
I find out this is the bug about row major norm
then I modify to use this:
`normalized_pts2d(:,1) = normalized_pts2d(:,1)./norm(normalized_pts2d(:,1));`
`normalized_pts2d(:,2) = normalized_pts2d(:,2)./norm(normalized_pts2d(:,2));`
`normalized_pts2d(:,3) = normalized_pts2d(:,3)./norm(normalized_pts2d(:,3));`

It's correct same as other algorithm:

R_est
ans(:,:,1) =

   0.542427   0.836628   0.076328
   0.022971  -0.105592   0.994144
   0.839789  -0.537497  -0.076494

ans(:,:,2) =

   0.7792449   0.0536202  -0.6244216
   0.0097686  -0.9972514  -0.0734450
  -0.6266435   0.0511319  -0.7776268
t_est
   -252.21   -267.02
    169.79    179.76
   1688.03   1787.14
